[package]
name = "rtracer-rs"
version = "0.1.0"
authors = ["alekspickle <aleks.work2222@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vek="0.9.9"
serde="1"
serde_derive="1"
image = "0.22.3"